### ISSUE TITLE
Crash when triggering .validate() twice

### ISSUE THREAD

**Issue by pedrovilela** [thyrlian/AwesomeValidation#62]
I got this exception when user clicking validate button twice

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: br.com.moneto, PID: 19109
                  java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                      at android.view.ViewGroup.addViewInner(ViewGroup.java:4937)
                      at android.view.ViewGroup.addView(ViewGroup.java:4768)
                      at android.view.ViewGroup.addView(ViewGroup.java:4708)
                      at com.basgeekball.awesomevalidation.utility.ViewsInfo.restoreViews(SourceFile:32)
                      at com.basgeekball.awesomevalidation.validators.UnderlabelValidator.halt(SourceFile:81)
                      at com.basgeekball.awesomevalidation.AwesomeValidation.clear(SourceFile:190)
                      at br.com.moneto.presentation.maqvirtual.MaqVirtualClientsNewActivity.saveClient(MaqVirtualClientsNewActivity.kt:77)
                      at br.com.moneto.presentation.maqvirtual.MaqVirtualClientsNewActivity$onCreate$1.onClick(MaqVirtualClientsNewActivity.kt:68)
                      at android.view.View.performClick(View.java:6294)
                      at android.view.View$PerformClick.run(View.java:24770)
                      at android.os.Handler.handleCallback(Handler.java:790)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by thyrlian** [comment]
Actually in the library's [code](https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/java/com/basgeekball/awesomevalidation/utility/ViewsInfo.java#L27), it `restoreViews` only when the ViewGroup is not original (`!mIsOriginal`).  I can imagine the only possibility of crashing here is it runs into race condition - calling multi-times in parallel.

I can try to investigate code from my side.  Meanwhile, could you please share some code snippets to help me reproduce the crash?  Thanks in advance.

**Comment by carlos-mg89** [comment]
I'm not sure if the same that happened to @pedrovilela is happening to me, but the thing is that I get the crash he's describing if I run 2 times the clear method of the `AwesomeValidation` object.

Aside from that, I'm seeing the validation errors as many times as I hit on `validate()`. I've attached a screenshot.

I just want to validate my form (simple form, 3 fields), but every time I press on "Register", it validates again and concatenates the previous validation. Even though I've called to `AwesomeValidation.clear()` before.

The validation clearing only works if I call to `AwesomeValidation.clear()` without calling to validate, right after that.

This is my code:

```
val mAwesomeValidation = AwesomeValidation(ValidationStyle.UNDERLABEL)
mAwesomeValidation.setContext(activity)
mAwesomeValidation.addValidation(activity, R.id.nameEditText, Pattern.compile("\\w+", Pattern.UNICODE_CASE), R.string.EmptyUserName)
mAwesomeValidation.addValidation(activity, R.id.emailEditText, android.util.Patterns.EMAIL_ADDRESS, R.string.EmailInvalid)
mAwesomeValidation.addValidation(activity, R.id.passwordEditText, Pattern.compile("\\w+", Pattern.UNICODE_CASE), R.string.EmptyPassword)
mAwesomeValidation.validate()
```

**Comment by carlos-mg89** [comment]
It only happens with the UNDERLABEL version. With other validation styles works like a charm.

**Comment by thyrlian** [comment]
Thanks @carlos-mg89 for reporting it.  May I ask where your above code snippet is triggered please?  Could you please also divide your code into different places?  For instance, the initialization of AwesomeValidation and addValidation at the beginning of the activity, then validate() inside some onClick method?
